dataset:
  repo_id: repo_multi_task_dit
  root: Datasets/example/four_types_merged

policy:
  type: multi_task_dit
  device: cuda
  push_to_hub: false
  horizon: 32
  n_action_steps: 24
  objective: diffusion
  noise_scheduler_type: DDPM
  num_train_timesteps: 100

  num_layers: 6
  hidden_dim: 512
  num_heads: 8
  vision_encoder_name: openai/clip-vit-base-patch16
  image_resize_shape: [320,240]
  image_crop_shape: [224,224]
  
  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]
  
  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/multi_task_dit
batch_size: 8
steps: 30000
save_freq: 5000
log_freq: 1000

wandb:
  enable: true
  project: multitask_dit
  entity: wangml71-zkyg
  mode: online
