job_name: wall_x_so101_softfold

dataset:
  repo_id: repo_wall_x
  root: Datasets/example/four_types_merged

policy:
  type: wall_x
  device: cuda
  push_to_hub: false
  repo_id: wangml71/wall_x_so101_softfold
  private:
  tags:
  license:
  pretrained_path: null
  pretrained_name_or_path: x-square-robot/wall-oss-flow
  prediction_mode: diffusion
  attn_implementation: eager

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]
  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/train/wall_x_training
batch_size: 1
steps: 6000
log_freq: 1000
save_freq: 5000
wandb:
  enable: false
